spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mariadb://localhost:3306/wchatdb?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    com.tutorial: debug
jwt:
  secret: kjasbdjkwqbtjkqnwgjkashu894y8129rbifsa67fg21bty78fshdfj95124bru789h124